<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_blocks',
		'title' => 'Blocks',
		'fields' => array (
			array (
				'key' => 'field_58a83e2b6f6b4',
				'label' => 'Block',
				'name' => 'block',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_58a83e466f6b5',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'flexible_content',
						'column_width' => '',
						'layouts' => array (
							array (
								'label' => 'Fullbredd bild/video',
								'name' => 'header',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_58a83ebc6f6b6',
										'label' => 'Background-image',
										'name' => 'background-image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'id',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
							),
							array (
								'label' => 'Två kolumn',
								'name' => 'two_column',
								'display' => 'row',
								'min' => '',
								'max' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_58b2b5ea3aa38',
										'label' => 'Bakgrundsfärg',
										'name' => 'background-color',
										'type' => 'color_picker',
										'column_width' => '',
										'default_value' => '',
									),
									array (
										'key' => 'field_58bf19550babb',
										'label' => 'Textfärg',
										'name' => 'text-color',
										'type' => 'color_picker',
										'column_width' => '',
										'default_value' => '',
									),
									array (
										'key' => 'field_58b2b4e4c7039',
										'label' => 'Sidinfo',
										'name' => 'siteinfo',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
									array (
										'key' => 'field_58b2b3bd31069',
										'label' => 'Kolumn 1 - bilder',
										'name' => 'pictures-column-one',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_58b2c68383b85',
												'label' => 'Padding',
												'name' => 'padding',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_58b2b41f3106b',
												'label' => 'Bild',
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'id',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_58b2b42e3106c',
												'label' => 'Bildtext',
												'name' => 'bylinetext',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'table',
										'button_label' => 'Add Row',
									),
									array (
										'key' => 'field_58b2b4043106a',
										'label' => 'Kolumn 2 - bilder',
										'name' => 'pictures-column-two',
										'type' => 'repeater',
										'column_width' => '',
										'sub_fields' => array (
											array (
												'key' => 'field_58b2c69883b86',
												'label' => 'Padding',
												'name' => 'padding',
												'type' => 'true_false',
												'column_width' => '',
												'message' => '',
												'default_value' => 0,
											),
											array (
												'key' => 'field_58b2b44e3106d',
												'label' => 'Bild',
												'name' => 'image',
												'type' => 'image',
												'column_width' => '',
												'save_format' => 'id',
												'preview_size' => 'thumbnail',
												'library' => 'all',
											),
											array (
												'key' => 'field_58b2b45b3106e',
												'label' => 'Bildtext',
												'name' => 'bylinetext',
												'type' => 'text',
												'column_width' => '',
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'formatting' => 'html',
												'maxlength' => '',
											),
										),
										'row_min' => '',
										'row_limit' => '',
										'layout' => 'table',
										'button_label' => 'Add Row',
									),
								),
							),
						),
						'button_label' => 'Add Row',
						'min' => '',
						'max' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-main.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}

